apiVersion: apps/v1
kind: Deployment
metadata:
  name: region-deployment
  namespace: distributed-app-region
  labels:
    app: app-region
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-region
  template:
    metadata:
      labels:
        app: app-region
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - us-west-2b
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.23
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
