apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: distributed-app-region
  labels:
    app: app-region
  name: region-nodeport
spec:
  ports:
    - name: 80-80
      nodePort: 30000
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-region
  type: NodePort
status:
  loadBalancer: {}
